// <auto-generated />
using System;
using CodeAlpha_DataRedundancyRemoval.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeAlpha_DataRedundancyRemoval.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260802120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phones, laptops, and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fiction and non-fiction books",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Everyday food and household items",
                            Name = "Groceries"
                        });
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Clifton, Karachi",
                            Email = "ayesha.khan@example.com",
                            Name = "Ayesha Khan",
                            Phone = "+92-300-1112222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gulshan-e-Iqbal, Karachi",
                            Email = "bilal.ahmed@example.com",
                            Name = "Bilal Ahmed",
                            Phone = "+92-301-2223333"
                        },
                        new
                        {
                            Id = 3,
                            Address = "DHA Phase 5, Karachi",
                            Email = "sara.malik@example.com",
                            Name = "Sara Malik",
                            Phone = "+92-302-3334444"
                        });
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 32.50m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 189.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 3,
                            UnitPrice = 12.25m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 49.99m
                        });
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Wireless Mouse",
                            Price = 15.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Mechanical Keyboard",
                            Price = 49.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "27-inch Monitor",
                            Price = 189.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Clean Code",
                            Price = 32.50m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "The Pragmatic Programmer",
                            Price = 29.75m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Organic Coffee Beans (1kg)",
                            Price = 12.25m,
                            Stock = 200
                        });
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Order", b =>
                {
                    b.HasOne("CodeAlpha_DataRedundancyRemoval.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.OrderDetail", b =>
                {
                    b.HasOne("CodeAlpha_DataRedundancyRemoval.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeAlpha_DataRedundancyRemoval.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Product", b =>
                {
                    b.HasOne("CodeAlpha_DataRedundancyRemoval.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CodeAlpha_DataRedundancyRemoval.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
